# This is a basic workflow to help you get started with Actions

name: build & deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Deploy Build
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd docs/.vuepress/dist
          git config --global user.email "hahohh@naver.com"
          git config --global user.name "docmoa"
          git init
          git add -A
          git commit -m 'deploy from github action'
          git branch -M main
          git push -f https://${ACCESS_TOKEN}@github.com/docmoa/docmoa.github.io.git main
